# Generated by Django 4.2.2 on 2024-04-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarDekho_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chasis Number:'),
        ),
        migrations.AddField(
            model_name='carlist',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Price'),
        ),
    ]
