# Generated by Django 4.2.2 on 2024-04-11 09:58

import CarDekho_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarDekho_app', '0002_carlist_chassis_number_carlist_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showroomlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name ')),
                ('location', models.CharField(max_length=150, verbose_name='Location')),
                ('website', models.URLField(verbose_name='URL')),
            ],
        ),
        migrations.AlterField(
            model_name='carlist',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[CarDekho_app.models.alphanumeric], verbose_name='Chasis Number'),
        ),
    ]
