# Generated by Django 4.2.2 on 2024-04-12 06:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarDekho_app', '0006_alter_review_car_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comments',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(10)], verbose_name='Rating'),
        ),
    ]
