# Generated by Django 4.2.2 on 2024-04-12 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CarDekho_app', '0010_review_apiuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='apiuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
