"""Initial migration

Revision ID: 0f1a4c399b21
Revises: 1b3c467e2aca
Create Date: 2024-08-14 19:35:29.929214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f1a4c399b21'
down_revision: Union[str, None] = '1b3c467e2aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_request', sa.Column('sample_id_2', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_request', 'sample_id_2')
    # ### end Alembic commands ###
