"""Initial migration 3

Revision ID: 2d9d78b13a2d
Revises: 0f1a4c399b21
Create Date: 2024-08-14 19:36:38.820693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d9d78b13a2d'
down_revision: Union[str, None] = '0f1a4c399b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_request', sa.Column('sample_id_3', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_request', 'sample_id_3')
    # ### end Alembic commands ###
